<a href="https://colab.research.google.com/github/Lelouch-VI-Britiania/data-science-toolkit/blob/library%2Fnumpy/wia1007_tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import numpy as np
array_2x2 = np.array([[1, 2],
            [3, 4]])
print("1. Numpy array (2x2):")
print(array_2x2)
print("\n")

1. Numpy array (2x2):
[[1 2]
 [3 4]]




In [6]:

random_3x4 = np.random.rand(3, 4)
print("2. Random numpy array (3x4):")
print(random_3x4)
print("\n")

2. Random numpy array (3x4):
[[0.20735241 0.94671505 0.38742351 0.7689222 ]
 [0.64753045 0.66084586 0.46961509 0.1754354 ]
 [0.77492109 0.37307829 0.8804598  0.26088653]]




In [5]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))
print("3. Array of Ones (2x3):")
print(ones_array)
print("Array of Zeroes (2x3):")
print(zeros_array)
print("\n")

3. Array of Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]
Array of Zeroes (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]




In [ ]:
random_6x3 = np.random.rand(6, 3)
transposed_array = random_6x3.T
print("4. Random array (6x3):")
print(random_6x3)
print("Transposed array (3x6):")
print(transposed_array)
print("\n")

In [ ]:
n, p, m = 2, 3, 4  # example sizes
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)

print("5. Matrix A (n x p):")
print(A)
print("Matrix B (p x m):")
print(B)
print("Dot product (A · B) -> (n x m):")
print(dot_product)